export const STRINGS = {
  // ---- Tab / Navigation ----
  TAB_HOME: '首页',
  TAB_TRAINING: '学习',
  TAB_DISCOVER: '活动',
  TAB_PROFILE: '我的',

  // ---- Index Page ----
  INDEX_PAGE_TITLE: '智天远小程序',
  INDEX_NAV_TITLE: '智能助手',
  INDEX_WELCOME_TITLE: '欢迎来到数字世界！',
  INDEX_WELCOME_SUB: '您可以直接向我提问，或者探索下方专区。',
  INDEX_PLACEHOLDER: '问我任何问题...',
  INDEX_COPY_WECHAT: '复制微信号',
  INDEX_LABEL_WECHAT: '微信号',
  INDEX_LABEL_PHONE: '电话',
  INDEX_AI_TEACHER: '为您找到以下 H3CNE 认证讲师的联系方式，您可以直接添加微信进行咨询。',
  INDEX_AI_EXAM: 'H3CNE 认证考试是新华三集团推出的网络工程师认证。报名流程：\n\n1️⃣ 确认报考条件（无学历/经验限制）\n2️⃣ 选择考试中心（全国 200+ 考点）\n3️⃣ 在线缴纳考试费\n4️⃣ 预约考试时间并参加考试\n\n以下是近期可报名的考试：',
  INDEX_AI_COURSE: '根据 H3CNE 考试大纲，为您精选以下学习课程。建议先从基础课程开始，再逐步深入：',
  INDEX_AI_COMPETITION: '为您查询到近期竞赛信息。当前有多个竞赛正在进行或即将开始，参与竞赛可获得实践经验和证书加分：',
  INDEX_AI_ACTIVITY: '近期平台有以下精彩活动，涵盖线上直播、线下沙龙和技术分享会：',
  INDEX_AI_EMPLOYMENT: '根据您的技能背景，为您匹配以下就业岗位。H3CNE 认证持有者在网络工程师岗位中优势明显：',
  INDEX_AI_DEFAULT: '收到您的问题，我正在为您整理相关信息。\n\n您也可以直接访问下方专区获取更详细的内容，或继续向我提问。',
  INDEX_ONLINE_COURSES: '在线课程',
  INDEX_TRAINING_ACTIVITIES: '在线培训',
  INDEX_VIEW_ALL: '全部',
  // ---- Zones Page ----
  ZONES_HEADER: '专区',
  ZONES_BANNER_TITLE: 'H3CNE 认证考试',
  ZONES_BANNER_DESC: '构建中小企业网络，开启网络工程师之路',
  ZONES_BANNER_BTN: '立即报名',
  ZONES_GRID_TITLE: '全部专区',
  ZONES_GRID_DETAIL: '查看详情',
  ZONE_NAMES: ['认证专区', '学习专区', '竞赛专区', '活动专区', '就业专区'] as const,

  // ---- Service Page ----
  SERVICE_HEADER: '人工客服',
  SERVICE_CARD_TITLE: '官方客服助理',
  SERVICE_CARD_SUBTITLE: '在线时间: 09:00 - 18:00',
  SERVICE_PHONE_LABEL: '电话咨询',
  SERVICE_WECHAT_LABEL: '微信客服',
  SERVICE_EMAIL_LABEL: '邮箱咨询',
  SERVICE_ACTION_CALL: '呼叫',
  SERVICE_ACTION_QR: '二维码',
  SERVICE_ACTION_COPY: '复制',
  SERVICE_PHONE_VALUE: '400-123-4567',
  SERVICE_WECHAT_VALUE: '扫码添加专属客服',
  SERVICE_EMAIL_VALUE: 'service@example.com',
  SERVICE_TICKETS_TITLE: '我的工单',
  SERVICE_TICKETS_EMPTY: '暂无工单',
  SERVICE_TICKETS_STATUS: '状态:',

  // ---- Profile Page ----
  PROFILE_MOCK_NAME: '小王同学',
  PROFILE_MOCK_STATUS: 'H3CNE 备考中',
  PROFILE_ORDERS: '我的订单',
  PROFILE_ALL_ORDERS: '全部订单',
  PROFILE_LOGOUT: '退出登录',
  PROFILE_GRID_CHECKIN: '打卡挑战',
  PROFILE_GRID_GROUP_BUY: '拼团资料',
  PROFILE_GRID_MY_COURSES: '我的课程',
  PROFILE_GRID_MY_FAVORITES: '我的收藏',
  PROFILE_LIST_ORDERS: '我的订单',
  PROFILE_LIST_SERVICE: '客服中心',
  PROFILE_LIST_SHARE: '分享给好友',
  PROFILE_FEATURE_IN_DEVELOPMENT: '功能开发中',
  PROFILE_SETTINGS: '设置',
  SETTINGS_ABOUT_US: '关于我们',
  SETTINGS_FEEDBACK: '意见反馈',
  SETTINGS_PERSONAL_INFO_LIST: '个人信息收集清单',
  SETTINGS_SWITCH_ACCOUNT: '切换账号',

  // ---- Orders Page ----
  ORDERS_TITLE: '我的订单',
  ORDERS_TAG_ALL: '全部',


  // ---- Auth Page ----
  AUTH_APP_NAME: 'H3CNE 数字世界',
  AUTH_APP_DESC: '开启您的网络工程师认证之旅',
  AUTH_WECHAT_BTN: '微信用户一键登录',
  AUTH_PHONE_BTN: '手机号快捷登录',
  AUTH_AGREEMENT_PREFIX: '我已阅读并同意',
  AUTH_AGREEMENT_TERMS: '《用户服务协议》',
  AUTH_AGREEMENT_PRIVACY: '《隐私政策》',
  AUTH_AGREEMENT_AND: '和',
  AUTH_AGREEMENT_SUFFIX: '，未注册手机号将自动注册',

  // ---- Exam Zone ----
  EXAM_TITLE: '考试专区',
  EXAM_TAG_ALL: '全部',
  EXAM_VIEW: '立即查看',
  EXAM_SIGNUP: '立即报名',
  EXAM_ALL_EXAMS: '全部考试',
  EXAM_SECTION_COUNT: '近7天10000+人报名',

  // ---- Study Zone ----
  STUDY_TITLE: '学习专区',
  STUDY_TAG_ALL: '全部课程',
  STUDY_ENROLL: '立即学习',

  // ---- Competition Zone ----
  COMPETITION_TITLE: '竞赛专区',
  COMPETITION_ONGOING: '进行中',
  COMPETITION_UPCOMING: '即将开始',
  COMPETITION_ENDED: '已结束',
  COMPETITION_TAG_ALL: '全部',
  COMPETITION_STATUS_REGISTERING: '报名中',
  COMPETITION_VIEW_RESULT: '查看结果',
  COMPETITION_SIGNUP: '立即报名',
  COMPETITION_SIGNUP_ENDED: '报名结束',
  COMPETITION_ENTER: '进入赛场',

  // ---- Activity Zone ----
  ACTIVITY_TITLE: '活动专区',
  ACTIVITY_DISCOUNT_SECTION: '精彩活动',
  ACTIVITY_ONGOING: '进行中',
  ACTIVITY_UPCOMING: '即将开始',
  ACTIVITY_ENDED: '已结束',
  ACTIVITY_TAG_ALL: '全部',
  ACTIVITY_VIEW_DETAIL: '查看详情',
  ACTIVITY_REMIND: '预约提醒',
  ACTIVITY_JOIN: '立即参与',

  // ---- Employment Zone ----
  EMPLOYMENT_TITLE: '就业专区',
  EMPLOYMENT_TAG_RECOMMEND: '推荐职位',
  EMPLOYMENT_TAG_ALL: '全部',
  EMPLOYMENT_APPLY: '立即投递',

  // ---- Registration Zone ----
  REGISTRATION_TITLE: '认证专区',
  REGISTRATION_SEARCH_PLACEHOLDER: '搜索认证项目',
  REGISTRATION_TAG_ALL: '全部',
  REGISTRATION_LOADING: '加载中...',
  REGISTRATION_EMPTY: '暂无认证项目',

  // ---- Phone Decrypt ----
  FORM_PHONE_WECHAT_AUTH: '微信一键授权',
  FORM_PHONE_WECHAT_AUTHING: '获取中...',

  // ---- Identity Check ----
  IDENTITY_CHECK_TITLE: '实名认证',
  IDENTITY_CHECK_DESC: '根据相关规定，报名认证考试需先完成实名认证',
  IDENTITY_CHECK_SUBMIT: '提交认证',
  IDENTITY_CHECK_SUBMITTING: '提交中...',
  IDENTITY_CHECK_FAILED: '认证提交失败，请重试',
  IDENTITY_PROFILE_INCOMPLETE: '请先完善个人信息（姓名、身份证号等），才能报名认证考试',
  IDENTITY_GOTO_PROFILE: '去完善资料',
  IDENTITY_VERIFYING: '正在提交实名认证...',

  // ---- Registration Form ----
  FORM_TITLE: '报名信息',
  FORM_EXAM_PREFERENCE: '考试偏好',
  FORM_CERT_SUMMARY: '认证项目',
  FORM_EXAM_DURATION: '考试时长',
  FORM_QUESTION_COUNT: '题目数量',
  FORM_PASSING_SCORE: '通过分数',
  FORM_REAL_NAME: '真实姓名',
  FORM_REAL_NAME_PLACEHOLDER: '请输入真实姓名',
  FORM_PHONE: '手机号码',
  FORM_PHONE_PLACEHOLDER: '请输入手机号码',
  FORM_ID_CARD: '身份证号',
  FORM_ID_CARD_PLACEHOLDER: '请输入身份证号',
  FORM_IDENTITY_TYPE: '身份类型',
  FORM_IDENTITY_PERSONAL: '个人报名',
  FORM_IDENTITY_ENTERPRISE: '企业报名',
  FORM_IDENTITY_STUDENT: '学生',
  FORM_ENTERPRISE_NAME: '企业名称',
  FORM_ENTERPRISE_NAME_PLACEHOLDER: '请输入企业名称',
  FORM_COUPON_SECTION: '考试券',
  FORM_COUPON_COUNT: '可用考试券',
  FORM_COUPON_COUNT_UNIT: '张',
  FORM_PRICE_DETAIL: '费用明细',
  FORM_PRICE_EXAM_FEE: '考试费',
  FORM_PRICE_COUPON_DISCOUNT: '考试券抵扣',
  FORM_PRICE_TOTAL: '合计',
  FORM_SUBMIT: '提交报名',
  FORM_PICK_EXAM_DATE: '请选择考试日期',

  // ---- Registration Confirm ----
  CONFIRM_TITLE: '确认报名',
  CONFIRM_ORDER_INFO: '订单信息',
  CONFIRM_CERT_NAME: '认证项目',
  CONFIRM_REAL_NAME: '真实姓名',
  CONFIRM_PHONE: '联系电话',
  CONFIRM_ID_CARD: '身份证号',
  CONFIRM_IDENTITY: '报名身份',
  CONFIRM_PAYMENT_METHOD: '支付方式',
  CONFIRM_PAYMENT_WECHAT: '微信支付',
  CONFIRM_AGREEMENT_PREFIX: '我已阅读并同意',
  CONFIRM_AGREEMENT_TERMS: '《报名须知》',
  CONFIRM_AGREEMENT_PRIVACY: '《隐私协议》',
  CONFIRM_PAY_BUTTON: '立即支付',
  CONFIRM_COUNTDOWN_PREFIX: '名额已锁定，请在 ',
  CONFIRM_COUNTDOWN_SUFFIX: ' 内完成支付',
  CONFIRM_COUNTDOWN_EXPIRED: '支付超时，请重新报名',

  // ---- Order Detail ----
  ORDER_DETAIL_TITLE: '订单详情',
  ORDER_DETAIL_AMOUNT_PAID: '实付款',
  ORDER_DETAIL_ORDER_ID: '订单编号',
  ORDER_DETAIL_COPY: '复制',
  ORDER_DETAIL_COPY_SUCCESS: '复制成功',
  ORDER_DETAIL_PAYMENT_METHOD: '支付方式',
  ORDER_DETAIL_PAYMENT_TIME: '支付时间',
  ORDER_DETAIL_ORDER_TIME: '下单时间',
  ORDER_DETAIL_PAYMENT_METHOD_WECHAT: '微信支付',

  // ---- Payment Result ----
  RESULT_SUCCESS_TITLE: '支付成功',
  RESULT_SUCCESS_DESC: '恭喜您报名成功，请按时参加考试',
  RESULT_FAIL_TITLE: '支付失败',
  RESULT_FAIL_DESC: '支付未完成，请重新尝试',
  RESULT_VIEW_ORDER: '查看订单',
  RESULT_REPAY: '重新支付',
  RESULT_BACK_HOME: '返回首页',

  // ---- Error Boundary ----
  ERROR_TITLE: '页面出现异常',
  ERROR_DESC: '请稍后重试或联系客服',

  // ---- Validation Messages ----
  VALIDATOR_NAME_REQUIRED: '请输入姓名',
  VALIDATOR_NAME_INVALID: '请输入2-20位中文姓名',
  VALIDATOR_PHONE_REQUIRED: '请输入手机号',
  VALIDATOR_PHONE_INVALID: '请输入正确的手机号',
  VALIDATOR_ID_CARD_REQUIRED: '请输入身份证号',
  VALIDATOR_ID_CARD_INVALID: '请输入正确的身份证号',

  // ---- Index Page Zones ----
  INDEX_ZONE_REGISTRATION: '认证专区',
  INDEX_ZONE_STUDY: '学习专区',
  INDEX_ZONE_COMPETITION: '竞赛专区',
  INDEX_ZONE_TRAINING: '培训专区',
  INDEX_ZONE_REGISTRATION_TITLE: 'H3CNE 认证考试',
  INDEX_ZONE_REGISTRATION_DESC: '构建中小企业网络，开启网络工程师之路',
  INDEX_ZONE_REGISTRATION_TAG: '新华三',
  INDEX_ZONE_STUDY_TITLE: '网络工程师入门到精通',
  INDEX_ZONE_STUDY_DESC: '零基础学习网络基础知识，TCP/IP协议，路由交换技术',
  INDEX_ZONE_STUDY_TAG: '热门',
  INDEX_ZONE_COMPETITION_TITLE: '2024全国大学生网络技术大赛',
  INDEX_ZONE_COMPETITION_DESC: '面向全国大学生的网络技术竞赛，展示技术实力',
  INDEX_ZONE_COMPETITION_TAG: '报名中',
  INDEX_ZONE_TRAINING_TITLE: '业务培训',
  INDEX_ZONE_TRAINING_DESC: '线上线下培训项目，助力技能提升',
  INDEX_ZONE_TRAINING_TAG: '即将上线',
  INDEX_ZONE_TRAINING_META: '敬请期待',
  INDEX_AI_NAME: '智小通',
  INDEX_AI_DESC: '您的专属 H3CNE 学习助手',
  INDEX_AI_CONSULT_BTN: '去咨询',

  // ---- AI Consult Page ----
  AI_CONSULT_HEADER_TITLE: '智小通咨询',
  AI_CONSULT_HEADER_NAME: '智小通',
  AI_CONSULT_HEADER_DESC: '您的专属学习与考证助手',
  AI_CONSULT_WELCOME: '您好!我是智小通,很高兴为您服务。\n\n我可以帮您:\n\n• 报名认证考试\n• 推荐学习课程\n• 提供讲师联系方式\n• 查询竞赛活动信息\n• 推荐就业岗位\n\n有什么我可以帮您的吗?',
  AI_TEACHER_NAME: '张老师',
  AI_TEACHER_TITLE: 'H3CNE 金牌讲师 / 考官',
  AI_TEACHER_WECHAT: 'H3C_TeacherZhang',
  AI_TEACHER_PHONE: '138-1234-5678',
  AI_EXAM_CARD_TITLE: 'H3CNE-RS 路由交换认证',
  AI_EXAM_CARD_DESC: '新华三认证网络工程师，企业网络构建与管理',
  AI_EXAM_CARD_TAG: '新华三',
  AI_EMPLOYMENT_CARD_NAME: '就业专区',
  AI_EMPLOYMENT_CARD_DESC: '热门网络工程师岗位推荐',
  AI_COMPETITION_CARD_NAME: '竞赛专区',
  AI_COMPETITION_CARD_DESC: '3个进行中 · 2个即将开始',
  AI_ACTIVITY_CARD_NAME: '活动专区',
  AI_ACTIVITY_CARD_DESC: '线上线下活动等你参与',
  AI_COURSE_CARD_TITLE: 'H3CNE 网络基础精讲',
  AI_COURSE_CARD_DESC: '从零基础到认证通关，含实验实操',
  AI_COURSE_CARD_DURATION: '48课时',
  AI_COURSE_CARD_TAG: '基础课程',

  // ---- Exam Zone ----
  EXAM_SUFFIX: '考试',

  // ---- Orders Page ----
  ORDERS_STATUS_PENDING: '待付款',
  ORDERS_STATUS_ENROLLED: '已报名',
  ORDERS_STATUS_CANCELLED: '已取消',
  ORDERS_FREE: '免费',

  // ---- Payment Result ----
  RESULT_ORDER_ID_PREFIX: '订单编号：',
  RESULT_ORDER_ID: '订单编号',
  RESULT_CERT_PROJECT: '认证项目',
  RESULT_PAID_AMOUNT: '实付金额',

  // ---- Registration Form Validation ----
  FORM_VALID_ENTERPRISE_NAME: '请输入企业名称',
  FORM_ERROR_CERT_NOT_FOUND: '认证项目不存在',
  FORM_QUESTION_SUFFIX: '题',
  FORM_SCORE_SUFFIX: '分',
  FORM_PERSONAL_INFO: '个人信息',
  FORM_COUPON_TIP: '使用1张考试券，抵扣考试费',

  // ---- Registration Confirm ----
  CONFIRM_PAYING: '支付中...',

  // ---- Logout Modal ----
  LOGOUT_MODAL_TITLE: '提示',
  LOGOUT_MODAL_CONTENT: '确定要退出当前账号吗？',
  LOGOUT_MODAL_CANCEL: '取消',
  LOGOUT_MODAL_CONFIRM: '退出',

  // ---- Func List ----

  // ---- AI Chat Cards ----
  AI_CARD_VIEW_DETAIL: '查看详情 →',
  AI_CARD_ENTER_ZONE: '进入专区 →',

  // ---- Mock Data ----
  MOCK_INDEX_WELCOME_MESSAGE: '您好！我是智天远智能助手 👋\n\n我可以帮您查询考试认证、推荐学习课程、了解竞赛活动、对接就业岗位。您可以直接向我提问，也可以点击下方专区入口快速浏览。\n\n请问有什么可以帮您的？',
  MOCK_QUICK_QUESTION_1: '如何报名 H3CNE 认证？',
  MOCK_QUICK_QUESTION_2: '有哪些学习课程推荐？',
  MOCK_QUICK_QUESTION_3: '最近有什么竞赛？',
  MOCK_QUICK_QUESTION_4: '帮我推荐就业方向',

  // ---- Exam Tag Labels ----
  EXAM_TAG_H3C: '新华三',
  EXAM_TAG_HUAWEI: '华为',
  EXAM_TAG_SANGFOR: '深信服',
  EXAM_TAG_RUANKAO: '软考',

  // ---- Competition ----
  COMPETITION_STATUS_RESERVING: '预约中',
  COMPETITION_BANNER_VIEW_MY: '查看我的竞赛',

  // ---- Activity Status ----
  ACTIVITY_STATUS_HOT: '火热进行中',
  ACTIVITY_STATUS_LONG_TERM: '长期有效',
  ACTIVITY_MY_PRIZES: '我的奖品',

  // ---- Study Tag Labels ----
  STUDY_TAG_BASIC: '基础课程',
  STUDY_TAG_ADVANCED: '进阶课程',
  STUDY_TAG_PRACTICAL: '实战课程',
  STUDY_TAG_CERTIFICATION: '认证课程',
  STUDY_VIEW_MY: '查看我的学习',

  // ---- Employment ----
  EMPLOYMENT_BANNER_TITLE: '好工作 好未来',
  EMPLOYMENT_BANNER_DESC: '海量优质岗位，专业就业指导，助你找到心仪工作',
  EMPLOYMENT_MY_JOBS: '我的求职',
  EMPLOYMENT_TAG_INTERN: '实习岗位',
  EMPLOYMENT_TAG_FULLTIME: '全职岗位',
  EMPLOYMENT_TAG_REMOTE: '远程岗位',

  // ---- Registration Tag Labels ----
  REGISTRATION_TAG_H3C: 'H3C',
  REGISTRATION_TAG_SANGFOR: '深信服',
  REGISTRATION_TAG_NISP: 'NISP',
  REGISTRATION_TAG_RS: '人社',

  // ---- Expanded Form Fields ----
  FORM_FIRST_NAME: 'FirstName（名）',
  FORM_FIRST_NAME_PLACEHOLDER: '请输入First Name',
  FORM_LAST_NAME: 'LastName（姓）',
  FORM_LAST_NAME_PLACEHOLDER: '请输入Last Name',
  FORM_GENDER: '性别',
  FORM_GENDER_MALE: '男',
  FORM_GENDER_FEMALE: '女',
  FORM_EMAIL: '电子邮件',
  FORM_EMAIL_PLACEHOLDER: '请输入邮箱地址',
  FORM_ID_PHOTO: '身份证人像面照片',
  FORM_ID_PHOTO_TIP: '支持JPG格式，文件小于5MB',
  FORM_EDUCATION: '学历',
  FORM_EDUCATION_PLACEHOLDER: '请选择学历',
  FORM_ORGANIZATION: '所在单位',
  FORM_ORGANIZATION_PLACEHOLDER: '请输入单位名称',
  FORM_EXAM_DATE: '考试时间',
  FORM_EXAM_DATE_PLACEHOLDER: '请选择考试时间',
  FORM_COUNTRY: '国别',
  FORM_COUNTRY_PLACEHOLDER: '请选择国家',
  FORM_LANGUAGE: '语言',
  FORM_LANGUAGE_PLACEHOLDER: '请选择语言',
  FORM_STUDENT_VERIFY: '学信网在线验证码',
  FORM_STUDENT_VERIFY_PLACEHOLDER: '请输入学信网验证码',
  FORM_XUEXIN_LINK_TEXT: '如何获取验证码？→',
  FORM_STUDENT_ID_PHOTO: '学生身份证明',
  FORM_STUDENT_ID_PHOTO_TIP: '请上传学生证照片',
  FORM_ENTERPRISE_BATCH_COUPON: '我为企业员工批量申请考试券',
  FORM_BATCH_COUNT: '申请数量',

  // ---- Sangfor Form ----
  SANGFOR_FORM_TITLE: '深信服认证报名',
  FORM_MAILING_ADDRESS: '邮寄地址',
  FORM_MAILING_ADDRESS_PLACEHOLDER: '请输入邮寄地址',
  FORM_EXAM_DIRECTION: '报考方向',
  FORM_EXAM_DIRECTION_PLACEHOLDER: '请选择报考方向',
  FORM_VERIFICATION_CODE: '动态验证码',
  FORM_VERIFICATION_CODE_PLACEHOLDER: '请输入深信服验证码',
  FORM_GET_VERIFY_CODE: '获取验证码',
  FORM_SANGFOR_COUPON_TIP: '支付成功后自动下发券码，不支持退换',

  // ---- NISP Form ----
  NISP_FORM_TITLE: 'NISP 认证报名',
  FORM_PINYIN: '拼音',
  FORM_MAJOR: '专业',
  FORM_MAJOR_PLACEHOLDER: '请输入专业',
  FORM_SCHOOL: '学校/单位名称',
  FORM_SCHOOL_PLACEHOLDER: '请输入学校或单位名称',
  FORM_PROVINCE: '报考省份',
  FORM_PROVINCE_PLACEHOLDER: '请选择省份',
  FORM_TRAINING_TYPE: '培训种类',
  FORM_PORTRAIT_PHOTO: '寸照',
  FORM_PORTRAIT_PHOTO_TIP_NISP1: 'PDF格式，命名：姓名+身份证号',
  FORM_PORTRAIT_PHOTO_TIP_NISP2: 'JPG格式 30KB-200KB，2寸蓝底，命名：姓名+身份证号',
  FORM_ID_PHOTO_TIP_NISP: 'PDF格式，身份证双面，命名：姓名',
  FORM_XUEXIN_REPORT: '教育部学籍在线验证报告',
  FORM_XUEXIN_REPORT_TIP: 'PDF格式，命名：姓名',
  FORM_TEMPLATE_DOWNLOAD: '下载NISP二级考试报名申请表模板',
  FORM_TEMPLATE_UPLOAD: '上传已填写的申请表（Word格式）',
  FORM_NISP_LEVEL: 'NISP等级',
  FORM_NISP_LEVEL_PLACEHOLDER: '请选择一级或二级',
  FORM_INSTITUTION: '培训机构',
  FORM_UPLOAD_PORTRAIT_PHOTO: '上传寸照',
  FORM_UPLOAD_ID_PHOTO: '上传身份证照片',
  FORM_UPLOAD_XUEXIN_REPORT: '上传学信网报告',
  NISP_INSTITUTION_DEFAULT: '四川智天远教育科技有限公司',
  NISP_LEVEL_1: 'NISP 一级',
  NISP_LEVEL_2: 'NISP 二级',
  NISP_PAY_SUCCESS_TOAST: '缴费成功，请等待审核通知',
  FORM_UPLOAD_MATERIALS: '上传材料',
  FORM_AGE: '年龄',
  FORM_AGE_PLACEHOLDER: '请输入年龄',
  FORM_ADDRESS: '地址',
  FORM_ADDRESS_PLACEHOLDER: '请输入地址',
  FORM_ZIP_CODE: '邮编',
  FORM_ZIP_CODE_PLACEHOLDER: '请输入邮编',
  FORM_NOTES: '备注',
  FORM_NOTES_PLACEHOLDER: '请输入备注信息...',

  // ---- Renshe Form ----
  RENSHE_FORM_TITLE: '人社认证报名',
  FORM_RENSHE_BRANCH: '认证分支',
  FORM_RENSHE_BRANCH_PLACEHOLDER: '请选择认证分支',
  RENSHE_BRANCH_NETWORK_SECURITY: '网络与信息安全',
  RENSHE_BRANCH_BUSINESS_DATA: '商务数据分析师',
  RENSHE_BRANCH_AI_ENGINEER: '人工智能工程师',
  RENSHE_BRANCH_IOT_ENGINEER: '物联网工程师',

  // ---- Xuexin Guide ----
  XUEXIN_GUIDE_TITLE: '学信网验证指引',
  XUEXIN_GUIDE_STEP1_TITLE: '第一步：打开学信网',
  XUEXIN_GUIDE_STEP1_DESC: '访问学信网 www.chsi.com.cn',
  XUEXIN_GUIDE_STEP2_TITLE: '第二步：登录学信档案',
  XUEXIN_GUIDE_STEP2_DESC: '使用账号密码或微信扫码登录',
  XUEXIN_GUIDE_STEP3_TITLE: '第三步：进入在线验证报告',
  XUEXIN_GUIDE_STEP3_DESC: '点击"在线验证报告"菜单',
  XUEXIN_GUIDE_STEP4_TITLE: '第四步：申请学籍验证报告',
  XUEXIN_GUIDE_STEP4_DESC: '申请"教育部学籍在线验证报告"',
  XUEXIN_GUIDE_STEP5_TITLE: '第五步：复制验证码',
  XUEXIN_GUIDE_STEP5_DESC: '复制报告中的在线验证码',
  XUEXIN_GUIDE_INPUT_LABEL: '在线验证码',
  XUEXIN_GUIDE_INPUT_PLACEHOLDER: '请输入学信网在线验证码',
  XUEXIN_GUIDE_CONFIRM: '确认使用',
  XUEXIN_GUIDE_INTRO: '请按以下步骤获取学信网在线验证码：',

  // ---- Training Tabs ----
  TRAINING_TAB_TECH: '技术培训',
  TRAINING_TAB_COURSE: '在线课程',
  TRAINING_TAB_QUIZ: '题库助手',
  TRAINING_FREE_COURSE: '免费课',
  TRAINING_PAID_COURSE: '付费课',

  // ---- Quiz ----
  QUIZ_HEADER: '刷题练习',
  QUIZ_CHECKIN_TITLE: '今日打卡',
  QUIZ_CHECKIN_STREAK: '已连续打卡',
  QUIZ_CHECKIN_DAYS: '天',
  QUIZ_CHECKIN_BTN: '去打卡',
  QUIZ_SECTION_PRACTICE: '章节练习',
  QUIZ_MOCK_EXAM: '模拟考试',
  QUIZ_CHALLENGE: '刷题挑战',
  QUIZ_ASSESSMENT: '能力测评',
  QUIZ_START_PRACTICE: '开始练习',
  QUIZ_PROGRESS: '进度',
  QUIZ_PREV: '上一题',
  QUIZ_NEXT: '下一题',
  QUIZ_SUBMIT: '提交',
  QUIZ_COLLECT: '收藏',
  QUIZ_UNCOLLECT: '取消收藏',
  QUIZ_MARK: '标记',
  QUIZ_RESULT_SCORE: '得分',
  QUIZ_RESULT_ACCURACY: '正确率',
  QUIZ_WRONG_BOOK_TITLE: '错题本',
  QUIZ_WRONG_BOOK_EMPTY: '暂无错题',
  QUIZ_WRONG_BOOK_REDO: '重新练习',
  QUIZ_WRONG_BOOK_REMOVE: '移出错题本',
  QUIZ_WRONG_COUNT: '错误次数',
  QUIZ_COLLECTIONS_TITLE: '收藏题目',
  QUIZ_COLLECTIONS_EMPTY: '暂无收藏',
  QUIZ_CHECKIN_CALENDAR: '打卡日历',
  QUIZ_CHECKIN_TODAY: '今日已打卡',
  QUIZ_CHECKIN_DONE: '已打卡',
  QUIZ_REDO: '再来一次',
  QUIZ_NO_QUESTIONS: '暂无题目',
  QUIZ_ANSWERED: '已答',
  QUIZ_TYPE_SINGLE: '单选题',
  QUIZ_TYPE_MULTIPLE: '多选题',
  QUIZ_FEEDBACK_CORRECT: '回答正确！',
  QUIZ_FEEDBACK_WRONG: '回答错误',
  QUIZ_CHECKIN_STATS_STREAK: '连续天数',
  QUIZ_CHECKIN_STATS_TOTAL: '累计打卡',
  QUIZ_CHECKIN_STATS_QUESTIONS: '累计刷题',

  // ---- Course ----
  COURSE_LIST_TITLE: '课程列表',
  COURSE_DETAIL_TITLE: '课程详情',
  COURSE_CATEGORY_ALL: '全部课程',
  COURSE_INSTRUCTOR: '讲师',
  COURSE_SESSIONS: '班次选择',
  COURSE_RATING: '评分',
  COURSE_REVIEWS: '评价',
  COURSE_ENROLL_BTN: '立即报名',
  COURSE_DESCRIPTION: '课程介绍',
  COURSE_SCHEDULE: '上课时间',
  COURSE_HOURS: '课时',
  COURSE_VIEW_DETAIL: '查看详情',
  COURSE_SELECT_SESSION_TOAST: '请选择班次',
  COURSE_ENROLL_SUCCESS: '报名成功',
  COURSE_NOT_FOUND: '课程不存在',

  // ---- Mine ----
  MINE_COURSES_TITLE: '我的课程',
  MINE_COURSES_ACTIVE: '正在学',
  MINE_COURSES_PENDING: '待开通',
  MINE_COURSES_EXPIRED: '已过期',
  MINE_COURSES_CONTINUE: '继续学习',
  MINE_COURSES_EMPTY: '暂无课程',
  MINE_PROFILE_TITLE: '个人资料',
  MINE_EDIT_PROFILE_TITLE: '编辑资料',
  MINE_PROFILE_EDIT_COUNT: '修改次数',
  MINE_PROFILE_SAVE: '保存',
  FORM_NICKNAME: '昵称',
  MINE_POINTS_TITLE: '积分优惠',
  MINE_POINTS_BALANCE: '我的积分',
  MINE_POINTS_HISTORY: '积分记录',
  MINE_POINTS_REDEEM: '兑换',
  MINE_POINTS_REDEEM_TIP: '每月可减免考试费¥50，上限¥100',
  MINE_AGREEMENTS_TITLE: '我的协议',
  MINE_AGREEMENTS_SIGN: '立即签署',
  MINE_AGREEMENTS_SIGN_CANVAS: '请在此处手写签名',
  MINE_AGREEMENTS_CLEAR: '清除重签',
  MINE_AGREEMENTS_SUBMIT: '提交签名',
  MINE_AGREEMENTS_DETAIL: '协议详情',
  MINE_COLLECTIONS_TITLE: '我的收藏',
  MINE_COLLECTIONS_COURSES: '课程收藏',
  MINE_COLLECTIONS_MATERIALS: '资料收藏',
  MINE_COLLECTIONS_EMPTY: '暂无收藏',
  MINE_EXAM_QUERY_TITLE: '报考查询',
  MINE_EXAM_QUERY_LINK: '查看报考链接',
  MINE_EXAM_QUERY_EMPTY: '暂无报考记录',
  MINE_EXAM_INTENTION_TITLE: '考试意向',
  MINE_EXAM_INTENTION_SAVE: '保存意向',
  MINE_CONTACT_TEACHERS_TITLE: '联系老师',
  MINE_CONTACT_PHONE: '电话',
  MINE_CONTACT_WECHAT: '微信',
  MINE_CONTACT_QQ: 'QQ',
  MINE_SHARE_TITLE: '分享好友',
  MINE_SHARE_APP: '分享小程序',
  MINE_SHARE_COURSE: '分享课程',
  MINE_SHARE_POSTER: '分享海报',
  MINE_DEACTIVATE_TITLE: '账号注销',
  MINE_DEACTIVATE_WARN: '注销后所有数据将被清除，无法恢复',
  MINE_DEACTIVATE_CONFIRM: '确认注销',
  MINE_DEACTIVATE_UNBIND: '解绑账号',
  MINE_DEACTIVATE_CHECKING: '正在检查注销条件...',

  // ---- Deactivate Page ----
  MINE_DEACTIVATE_CONDITION_1: '账户无未完成订单',
  MINE_DEACTIVATE_CONDITION_2: '无进行中的培训协议',
  MINE_DEACTIVATE_CONDITION_3: '已绑定手机号',
  MINE_DEACTIVATE_CONDITION_4: '账户余额为零',
  MINE_DEACTIVATE_CHECK_TITLE: '注销条件检查',
  MINE_DEACTIVATE_UNBIND_HINT: '请先解绑以下绑定，再进行注销操作。',
  MINE_DEACTIVATE_CONTINUE: '继续注销',
  MINE_DEACTIVATE_CONFIRM_TITLE: '确认注销',
  MINE_DEACTIVATE_CONFIRM_DESC: '注销后，您的所有数据将被永久删除，无法恢复。包括但不限于：订单记录、学习进度、积分余额、课程收藏等。',
  MINE_DEACTIVATE_CANCEL: '暂不注销',
  MINE_DEACTIVATE_SUCCESS: '注销申请已提交',
  MINE_DEACTIVATE_MOCK_PHONE: '手机号: 138****8888',
  MINE_DEACTIVATE_MOCK_WECHAT: '微信: 已绑定',

  // ---- Agreements Page ----
  MINE_AGREEMENTS_CREATE: '新建协议',
  MINE_AGREEMENTS_CREATE_FAIL: '创建失败',
  MINE_AGREEMENTS_STATUS_PENDING_SIGN: '待签署',
  MINE_AGREEMENTS_STATUS_PENDING_REVIEW: '待审核',
  MINE_AGREEMENTS_STATUS_STAMPED: '已签章',
  MINE_AGREEMENTS_STATUS_COMPLETED: '已完成',
  MINE_AGREEMENTS_SIGN_HINT: '请在屏幕上签名',
  MINE_AGREEMENTS_SIGN_SUCCESS: '签名提交成功',
  MINE_AGREEMENTS_SIGN_TIME: '签署时间:',

  // ---- Exam Intention Page ----
  MINE_EXAM_INTENTION_HINT: '选择感兴趣的认证',
  MINE_EXAM_INTENTION_SAVED: '意向已保存',

  // ---- Contact Teachers Page ----
  MINE_CONTACT_WECHAT_COPIED: '微信号已复制',
  MINE_CONTACT_QQ_COPIED: 'QQ号已复制',

  // ---- Exam Query Page ----
  MINE_EXAM_LINK_COPIED: '链接已复制',

  // ---- Profile Edit Page ----
  MINE_PROFILE_EDIT_EXHAUSTED: '修改次数已用完',
  MINE_PROFILE_SAVE_SUCCESS: '保存成功',

  // ---- Share Page ----
  MINE_SHARE_APP_DESC: '分享小程序给微信好友',
  MINE_SHARE_COURSE_DESC: '推荐课程给朋友',
  MINE_SHARE_POSTER_DESC: '生成专属推广海报',
  MINE_SHARE_DEFAULT_LABEL: '分享',

  // ---- Courses Page ----
  MINE_COURSES_UNIT: '节',

  // ---- Login Poster ----
  LOGIN_POSTER_TITLE: '活动推荐',
  LOGIN_POSTER_CLOSE: '关闭',
  LOGIN_POSTER_CLAIMED: '已领取',
  LOGIN_POSTER_WELCOME: '欢迎回来！以下是近期活动和优惠：',
  LOGIN_POSTER_CLAIM_NOW: '立即领取',
  LOGIN_POSTER_VIEW_DETAIL: '查看详情',
  LOGIN_POSTER_CARD_1_TITLE: '2026全国大学生网络技术大赛',
  LOGIN_POSTER_CARD_1_DESC: '火热报名中！赢取万元奖金与名企实习机会',
  LOGIN_POSTER_CARD_1_TAG: '竞赛',
  LOGIN_POSTER_CARD_2_TITLE: 'H3CNE 认证暑期特惠',
  LOGIN_POSTER_CARD_2_DESC: '学生价立减400元，限时优惠',
  LOGIN_POSTER_CARD_2_TAG: '优惠券',
  LOGIN_POSTER_CARD_3_TITLE: '网络安全技能培训营',
  LOGIN_POSTER_CARD_3_DESC: '暑假集训班报名开启，名额有限',
  LOGIN_POSTER_CARD_3_TAG: '活动',

  // ---- Validation ----
  VALIDATOR_EMAIL_REQUIRED: '请输入邮箱',
  VALIDATOR_EMAIL_INVALID: '请输入正确的邮箱地址',
  VALIDATOR_VERIFICATION_REQUIRED: '请输入验证码',
  VALIDATOR_SCHOOL_REQUIRED: '请输入学校名称',
  VALIDATOR_ORGANIZATION_REQUIRED: '请输入单位名称',
  VALIDATOR_ADDRESS_REQUIRED: '请输入地址',

  // ---- Tags ----
  TAG_H3C: '华三',
  TAG_SANGFOR: '深信服',
  TAG_NISP: 'NISP',
  TAG_RENSHE: '人社',
  TAG_FREE: '免费',
  TAG_PAID: '付费',
  WEEKDAY_LABELS: ['日', '一', '二', '三', '四', '五', '六'] as const,
  CALENDAR_YEAR_SUFFIX: '年',
  CALENDAR_MONTH_SUFFIX: '月',
} as const